#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
START=${1}
END=${2}
FILENAME=${3-"${DIR}/../sample_data/nurses.json"}

if [[ -z $START || -z $END ]]; then
  echo -e  "Please pass a start and end date\n";
  echo "     $ ${0} <START_DATE> <END_DATE> [filename]";
  echo "e.g. $ ${0} 2020-01-01 2020-02-03";
  exit 1
fi

yarn start --start-date="$START" --end-date="$END" --filename="${FILENAME}"
